* To Laria
an analogy i gave my mentor from church was that people have an invariant form.

i have an identity i want to protect from others that tell me how to think and act, what to believe and not believe. but take away the external influences or overcome personal anxiety and become more self affirming to find your invariant.

a message or advice to a person is transfromative if they take it to heart.

it may be the thing that polishes a diamond but could corrode a fossil.

the invariant of a fossil isn't the need for carbon atoms as is a diamond, but rather its beautiful shape which retains the image of what it represents.

so people have an an identity they should protect.

my memories of the past in some sense, even the early ones are more crystalised and easier to recall because they are my identity now but i still consider myself to have an identity beyond just being a collection of memories. but part of my memory me i guess is always feeling loved. and i was clothed as i walked out the door into adulthood.

only like after going to uni had i kinda started to get disillusioned.

if i take this allegory and apply it to my parents and ancestors i have to give weight to messages from the past and i don't want to lose my clothes/identity i have been endowed with. are created to create and to break walls.

with the tomato bear story i was thinking of going from a place where they had lost their identity to one where they find it again.