* The tomato bear
- avoid allegory and generalisation?

A tomato is nothing by itself. It needs a bear.

The tomato bear lives in a world of fake plants. It wasn't always that way.

There was a time when a bears learned to care for the plants and plant,
hedgehog and snail would live in harmony.

The tomato bear is the bearer of a real plant.
Real plants can philosophize.
Real plants have a telos.
 the full potential or inherent purpose or objective of a person or thing, similar to the notion of an 'end goal' or 'raison d'être'. Moreover, it can be understood as the "supreme end of man's endeavour."
A real plant dreams of being a plant to its fullest potential and that means ...
Aside from growing into a fully grown plant, a real plant ...
Fake plants 

The tomato bear is the bearer of a tomato... what is special about the tomato over other plants?
The tomato bear 

Bears are smaller than tomatoes
The tomato bear comes from a small village of bears
The tomato bear has allowed

There are different types of tomato bears.
- Cherry tomato
- Big tomato

Cherry tomatoes

An evil creature that created the virus that kills tomatoes. The nihilist 
The bear is able to keep the tomato alive.
And in keeping the tomato alive, also its philosophy

The mushroom people have a mushroom on their heads.
They are not baddies, but each type of plant has a different philosophy and the mushrooms are very different.

The mushroom people and mushroom land.

All plants are good but some of them have
fallen under the influence of the nihilist
philosophy and they don't believe as they once
did and so have started to impose their own
philosophy onto others?

The big tomato believes its telos is not to be made into ketchup? -- maybe this is too comical
The big tomato is very old and wise.

The big tomato's philosophy

Bears are very bearish.

It has caused the cherry tomatoes that once grew in bunches on the ground to divide against themselves.

Fake plants are a lot like fake 
- grapes
- flowers
They no longer interact with anything.

The tomato bear visits the bees.
The bees are about 1/4 the size of the tomato bear and live at the twin hives.

   ~~~       ~~~ 
 /-----\   /-----\
|-------| |-------|
|-------| |-------|
|--/ \--| |--/ \--|